const newsData = [
    // FILA 1
    { fecha: "1941", resumen: "A inicios de los 40's Irán se encontraba ocupada por las fuerzas aliadas. Aunque Estados Unidos y Gran Bretaña se retiraron al finalizar la segunda guerra mundial, no lo hizo de esta manera la Unión Soviética.", fila: 1 },
    { fecha: "1946", resumen: "Los iraníes pro soviéticos comenzaron una guerra interna, la que se conoció como la crisis de Irán de 1946. Ello terminó con la proclamación de la separatista República Popular de Azerbaiyán.", fila: 1 },
    { fecha: "1946-1951", resumen: "Finalizada la guerra, una coalición de nacionalistas, clérigos y partidos de izquierda no comunistas, se unió bajo Mohammad Mosaddegh, quien deseaba reducir el poder la monarquía y el clero en Irán.", fila: 1 },
    { fecha: "1951", resumen: "Mohammad Mosaddegh se convierte en Primer Ministro de Irán e inmediatamente nacionaliza el petróleo. En ese momento Gran Bretaña era el principal benefactor del petróleo iraní e impuso un embargo económico a Irán.", fila: 1 },
    { fecha: "1953", resumen: "Internamente el apoyo a Mosaddegh se debilitó por el bajo desempeño de sus políticas sociales y económicas. En agosto de 1953 huye del país debido a un golpe de estado financiado por la CIA.", fila: 1 },
    { fecha: "1954", resumen: "Con la caída de Mohammad Mosaddegh finaliza la nacionalización del petróleo iraní. En 1954 un consorcio multinacional liderado por 'British Petroleum' acelera el desarrollo petrolero iraní.", fila: 1 },    

    // FILA 2
    { fecha: "1960-1963", resumen: "Durante este periodo, Irán experimentó cambios políticos y económicos significativos. Entre ellos destacan la modernización industrial y el crecimiento económico impulsado por los ingresos petroleros. Además, existieron grandes avances en materia de derechos humanos y de la mujer.", fila: 2 },
    { fecha: "1963", resumen: "Comienza a manifestarse resistencia contra las reformas de sha, Mohammad Reza Pahlavi, especialmente dentro de la comunidad chiita. Es en este contexto que la figura del ayatolá Ruhollah Khomeini comienza a ganar popularidad pese a su exilio.", fila: 2 },
    { fecha: "1970-1975", resumen: "Durante este quinquenio el sha impulsó una serie de reformas económicas que culminaron en una crisis económica, acelerando el descontento hacia su figura. Por otro lado Khomeini vuelve a ser relevante en el ámbito social y político, y muchos argumentan que Irán debe regresar a su cultura autóctona (clerical).", fila: 2 },
    { fecha: "1978", resumen: "La sensación de corrupción en el Gobierno iraní exacerbó los ánimos contra el régimen. Es así como en enero de 1978 comienzan una serie de protestas contra el sha, terminado con la muerte de muchos de los manifestantes. Lo que solo alimentó el descontento social.", fila: 2 },
    { fecha: "1978", resumen: "Desde su exilio en Francia, Khomeini coordinó el recrudecimiento de la oposición contra el régimen. En enero de 1979 el sha huye de Irán y muere al año siguiente en Egipto.", fila: 2 },
    { fecha: "1979", resumen: "El 1 de abril, con el apoyo del referéndum nacional, Khomeini declaró a Irán como una república islámica, imponiendo un retorno a los valores sociales conservadores. Además, creó la Guardia Revolucionaria con el propósito de reprimir cualquier golpe de Estado.", fila: 2 },

    // FILA 3
    { fecha: "1989", resumen: "Después de un periodo de guerra contra Irak por disputas territoriales, el ayatolá Khomeini muere en enero de este año y comienzan los preparativos para su sucesión. El elegido fue Alí Khamenei quien fue el líder supremo de Irán desde esta fecha hasta su muerte en 2026.", fila: 3 },
    { fecha: "1989-2001", resumen: "Comenzó un periodo de declive en las relaciones entre Estados Unidos e Irán. Principalmente debido a que Irán se oponía a las invasiones estadounidenses en la región, en especial después de los ataques del 11 de septiembre de 2001.", fila: 3 },
    { fecha: "2002", resumen: "El programa nuclear iraní acaparó la atención internacional cuando un grupo disidente al régimen reveló que Irán estaba construyendo en secreto una planta de enriquecimiento de uranio. Aunque Irán insistió en que sus actividades tenían fines pacíficos.", fila: 3 },
    { fecha: "2006", resumen: "El Consejo de Seguridad de la ONU impuso las primeras sanciones dirigidas al programa nuclear.", fila: 3 },
    { fecha: "2015", resumen: "Una coalición integrada por Estados Unidos, China, Rusia, Francia, Alemania y Reino Unido, alcanzaron un acuerdo junto a Irán para restringir y supervisar su programa nuclear.", fila: 3 },
    { fecha: "2018", resumen: "El presidente de los Estados Unidos, Donald Trump, anunció la salida de Estados Unidos del acuerdo previamente alcanzado y afirmó que reanudaría las sanciones económicas contra Irán.", fila: 3 },
    { fecha: "2025", resumen: "Estados Unidos e Israel lanzan multiples ataques contra Irán, alegando que Irán se encuentra cerca del desarrollo de la bomba nuclear. El conflicto finalizó pronto, en lo que se denominó como la guerra de los 12 días.", fila: 3 },

    // FILA 4
    { fecha: "enero 2026", resumen: "El año comienza entre disturbios en Irán y el despliegue de fuerzas militares estadounidenses cerca de aguas iranies.", fila: 4 },    
    { fecha: "28 de febrero 2026", resumen: "Estados Unidos e Israel atacan Irán mientras había conversaciones para tratar de lograr consenso sobre el programa nuclear iraní y su programa de misiles. El mismo día del ataque Irán responde cerrando el Estrecho de Ormuz.", fila: 4 },
    { fecha: "29 de febrero 2026", resumen: "Irán ataca bases militares estadounidenses ubicadas en países del Golfo Pérsico, pero los ataques se extienden a infraestructura energética de países como Arabia Saudita, Qatar, Dubái o Baréin.", fila: 4 },    
    { fecha: "9 de marzo 2026", resumen: "El fin de semana del 7 al 8 de marzo Estados Uniods e Israel atacan depósitos de petróleo iraniés. El lunes 9 los mercados de petróleo experimenta la mayor variación porcentual en su precio desde que se tienen registros de precios de futuros del mismo.", fila: 4 },
    { fecha: "23 de marzo 2026", resumen: "Finaliza el primer ultimátum de Estados Unidos a Irán, pero el ataque se pospone por 5 días. Estados Unidos argumenta que comienza una serie de conversaciones en torno a un posible acuerdo de paz."},
    { fecha: "7 de abril 2026", resumen: "Este día finalizaría el segundo ultimátum de Estados Unidos a Irán. Antes de cumplirse el ultimátum, Pakistán logra un acuerdo de cese al fuego mientras se llevan a cabo conversaciones entre las partes."},
    { fecha: "11 y 12 de abril 2026", resumen: "Delegados estadounidenses e iraníes se reúnen en Islamabad para intentar llegar a un acuerdo. Pese a ello no se llega a un consenso y Estados Unidos declara un bloqueo naval a Irán."},
    { fecha: "13 de abril 2026", resumen: "Estados Unidos impone un bloqueo a los principales puertos de exportación. El objetivo es impedir la entrada y salida de buques de puertos iraníes."},
    { fecha: "17 de abril 2026", resumen: "Irán abre el estrecho de Ormuz dentro del contexto del cese al fuego pactado por ambas partes, pero decide bloquearlo nuevamente debido al bloqueo estadounidense, el cual califican de piratería."},
    { fecha: "21 de abril 2026", resumen: "Se tenía prevista una segunda ronda de negociaciones en Islamabad entre delegados de alto nivel de Estados Unidos e Irán. Esta se suspendió debido a que Irán no negociará con Estados Unidos mientras continue el bloqueo. Por su parte, el gobierno estadounidense extiende el cese al fuego de forma indefinida, pero mantiene el bloqueo sobre Irán."},
    { fecha: "28 de abril 2026", resumen: "Distintos medios han reportado de una propuesta iraní para abrir nuevamente el Estrecho de Ormuz. En ella se incluye el fin de las hostilidades contra Irán, así como del bloqueo estadounidense. Dicha propuesta aun es evaluada por Estados Unidos, pero no ha convencido a la Casa Blanca debido a que deja por fuera de las conversaciones el enriquecimiento de uranio por parte de Irán."},
    { fecha: "5 de mayo 2026", resumen: "Irán atacó a Emiratos Árabes Unidos como respuesta a la operación Project Freedom (iniciativa de Estados Unidos para liberar el Estrecho de Ormuz). Esto pone en dudas la continuidad del alto al fuego pactado el 8 de abril entre ambas partes."},
    { fecha: "6 de mayo 2026", resumen: "Ha destacado la noticia que Estados Unidos e Irán podrían firmar un memorando para poner fin a la guerra. Es por este motivo que los mercados han respondido positivamente haciendo qu el precio del petróleo cayera"},
];